# Generated by Django 4.2.15 on 2024-08-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish'), ('pending', 'Pending')], default='draft', max_length=50),
        ),
    ]
