# Generated by Django 4.2.15 on 2024-08-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_saff',
            new_name='is_staff',
        ),
    ]
